/***************************************************************************
  This file was created by the program FALCO which is a module 
  of WinFACT (Windows Fuzzy And Control Tools).

  Instead of editing this file, modify FALCOs Source-File
  with FLOP and generate it once again.

  Generated by : Florian
            on : DESKTOP-N6QTDVR
  FALCO Version: 8.0.0.9
  Source-File  : C:\Users\Florian\Documents\SCHULE\Diplomarbeit\Fuzzy\FC_v.fuz from:28.12.2019 12:09:02
  Timestamp    : 04.01.2020 21:18:04

  Description of the fuzzy controller implemented in this code:
  =============================================================

    Inputs: 2
     e
     e_int

    Outputs: 1
     u

    Rules: 10

    Inferencemechanism: Max-Min
    Method of defuzzyfication: center of gravity (Intergration via 60 steps)
    Number format: 4 Byte IEEE float
***************************************************************************/

#ifndef FC_v_F4
#define FC_v_F4 FC_v_F4



#include "fuzzy_F4.h"

#ifdef __cplusplus
  extern "C" {
#endif

void FC_v_F4_SetNumType(void);

void FC_v_F4_init(void);

void FC_v_F4_calc(
       const NumTypeF4_t i0,
       const NumTypeF4_t i1,
       NumTypeF4_t *o0);

void FC_v_F4_free(void);
#ifdef __cplusplus
  }
#endif
extern FuzzyControllerF4_t FC_v_F4_FC;


#endif
