/***************************************************************************
  This file was created by the program FALCO which is a module 
  of WinFACT (Windows Fuzzy And Control Tools).

  Instead of editing this file, modify FALCOs Source-File
  with FLOP and generate it once again.

  Generated by : Florian
            on : DESKTOP-N6QTDVR
  FALCO Version: 8.0.0.9
  Source-File  : C:\Users\Florian\Documents\SCHULE\Diplomarbeit\Fuzzy\FuzzyTry.fuz from:04.01.2020 19:04:16
  Timestamp    : 04.01.2020 20:04:49

  Description of the fuzzy controller implemented in this code:
  =============================================================

    Inputs: 2
     geschwindigkeit
     winkel

    Outputs: 2
     vOUT
     phiOUT

    Rules: 10

    Inferencemechanism: Max-Min
    Method of defuzzyfication: center of gravity (Intergration via 60 steps)
    Number format: 4 Byte IEEE float
***************************************************************************/

#ifndef FuzzyTry_F4
#define FuzzyTry_F4 FuzzyTry_F4



#include "fuzzy_F4.h"

#ifdef __cplusplus
  extern "C" {
#endif

void FuzzyTry_F4_SetNumType(void);

void FuzzyTry_F4_init(void);

void FuzzyTry_F4_calc(
       const NumTypeF4_t i0,
       const NumTypeF4_t i1,
       NumTypeF4_t *o0,
       NumTypeF4_t *o1);

void FuzzyTry_F4_free(void);
#ifdef __cplusplus
  }
#endif
extern FuzzyControllerF4_t FuzzyTry_F4_FC;


#endif
