/***************************************************************************
  This file was created by the program FALCO which is a module 
  of WinFACT (Windows Fuzzy And Control Tools).

  Instead of editing this file, modify FALCOs Source-File
  with FLOP and generate it once again.

  Generated by : Florian
            on : DESKTOP-N6QTDVR
  FALCO Version: 8.0.0.9
  Source-File  : C:\Users\Florian\Documents\SCHULE\Diplomarbeit\NeueCodeGenerierung\V3\FuzzyV3.fuz from:04.01.2020 12:44:50
  Timestamp    : 04.01.2020 12:46:13

  Description of the fuzzy controller implemented in this code:
  =============================================================

    Inputs: 1
     e_winkel

    Outputs: 1
     u_winkel

    Rules: 5

    Inferencemechanism: Max-Min
    Method of defuzzyfication: center of gravity (Intergration via 60 steps)
    Number format: 4 Byte IEEE float
***************************************************************************/

#ifndef FuzzyV3_F4
#define FuzzyV3_F4 FuzzyV3_F4



#include "fuzzy_F4.h"

#ifdef __cplusplus
  extern "C" {
#endif

void FuzzyV3_F4_SetNumType(void);

void FuzzyV3_F4_init(void);

void FuzzyV3_F4_calc(
       const NumTypeF4_t i0,
       NumTypeF4_t *o0);

void FuzzyV3_F4_free(void);
#ifdef __cplusplus
  }
#endif
extern FuzzyControllerF4_t FuzzyV3_F4_FC;


#endif
