/***************************************************************************
  This file was created by the program FALCO which is a module 
  of WinFACT (Windows Fuzzy And Control Tools).

  Instead of editing this file, modify FALCOs Source-File
  with FLOP and generate it once again.

  Generated by : Florian
            on : DESKTOP-N6QTDVR
  FALCO Version: 8.0.0.9
  Source-File  : C:\Users\Florian\Documents\SCHULE\5AHET\Diplomarbeit\WinFact\LKWRangierenFuzzy\rangierFuzzy.fuz from:03.11.2019 20:06:00
  Timestamp    : 17.11.2019 08:15:29

  Description of the fuzzy controller implemented in this code:
  =============================================================

    Inputs: 2
     e1
     e2

    Outputs: 2
     a1
     a2

    Rules: 9

    Inferencemechanism: Max-Min
    Method of defuzzyfication: center of gravity (Intergration via 60 steps)
    Number format: 4 Byte IEEE float
***************************************************************************/

#ifndef rangierFuzzy_F4
#define rangierFuzzy_F4 rangierFuzzy_F4



#include "fuzzy_F4.h"

#ifdef __cplusplus
  extern "C" {
#endif

void rangierFuzzy_F4_SetNumType(void);

void rangierFuzzy_F4_init(void);

void rangierFuzzy_F4_calc(
       const NumTypeF4_t i0,
       const NumTypeF4_t i1,
       NumTypeF4_t *o0,
       NumTypeF4_t *o1);

void rangierFuzzy_F4_free(void);
#ifdef __cplusplus
  }
#endif


#endif
