/***************************************************************************
  This file was created by the program FALCO which is a module 
  of WinFACT (Windows Fuzzy And Control Tools).

  Instead of editing this file, modify FALCOs Source-File
  with FLOP and generate it once again.

  Generated by : Florian
            on : DESKTOP-N6QTDVR
  FALCO Version: 8.0.0.9
  Source-File  : C:\Users\Florian\Documents\SCHULE\Diplomarbeit\Fuzzy\Winfact\testdiplom.fuz from:22.10.2019 16:52:52
  Timestamp    : 22.10.2019 17:01:42

  Description of the fuzzy controller implemented in this code:
  =============================================================

    Inputs: 1
     e

    Outputs: 1
     u

    Rules: 3

    Inferencemechanism: Max-Min
    Method of defuzzyfication: center of gravity (Intergration via 60 steps)
    Number format: 4 Byte IEEE float
***************************************************************************/

#ifndef testdiplom_F4
#define testdiplom_F4 testdiplom_F4



#include "fuzzy_F4.h"

#ifdef __cplusplus
  extern "C" {
#endif

void testdiplom_F4_SetNumType(void);

void testdiplom_F4_init(void);

void testdiplom_F4_calc(
       const NumTypeF4_t i0,
       NumTypeF4_t *o0);

void testdiplom_F4_free(void);
#ifdef __cplusplus
  }
#endif


#endif
