/***************************************************************************
  This file was created by the program FALCO which is a module 
  of WinFACT (Windows Fuzzy And Control Tools).

  Instead of editing this file, modify FALCOs Source-File
  with FLOP and generate it once again.

  Generated by : Florian
            on : DESKTOP-N6QTDVR
  FALCO Version: 8.0.0.9
  Source-File  : C:\Users\Florian\Documents\SCHULE\Diplomarbeit\Fuzzy\FC_v.fuz from:28.12.2019 12:09:02
  Timestamp    : 04.01.2020 21:18:04

  Description of the fuzzy controller implemented in this code:
  =============================================================

    Inputs: 2
     e
     e_int

    Outputs: 1
     u

    Rules: 10

    Inferencemechanism: Max-Min
    Method of defuzzyfication: center of gravity (Intergration via 60 steps)
    Number format: 4 Byte IEEE float
***************************************************************************/

#include "FC_v_F4.h"

/*############################################################################*/
/*                        Sets of all input variables                         */
/*############################################################################*/

NumTypeF4Point_t FC_v_F4_e_0_NegBig[3]={
   {-30, 0},
   {-30, 1},
   {-15, 0}};
NumTypeF4Point_t FC_v_F4_e_1_NegSmall[3]={
   {-30, 0},
   {-15, 1},
   {0, 0}};
NumTypeF4Point_t FC_v_F4_e_2_Zero[3]={
   {-15, 0},
   {0, 1},
   {15, 0}};
NumTypeF4Point_t FC_v_F4_e_3_PosSmall[3]={
   {0, 0},
   {15, 1},
   {30, 0}};
NumTypeF4Point_t FC_v_F4_e_4_PosBig[3]={
   {15, 0},
   {30, 1},
   {30, 0}};

NumTypeF4Point_t FC_v_F4_e_int_0_NegBig[3]={
   {-30, 0},
   {-30, 1},
   {-15, 0}};
NumTypeF4Point_t FC_v_F4_e_int_1_NegSmall[3]={
   {-30, 0},
   {-15, 1},
   {0, 0}};
NumTypeF4Point_t FC_v_F4_e_int_2_Zero[1]={
   {0, 1}};
NumTypeF4Point_t FC_v_F4_e_int_3_PosSmall[3]={
   {0, 0},
   {15, 1},
   {30, 0}};
NumTypeF4Point_t FC_v_F4_e_int_4_PosBig[3]={
   {15, 0},
   {30, 1},
   {30, 0}};

/*############################################################################*/
/*                        Sets of all output variables                        */
/*############################################################################*/

NumTypeF4Point_t FC_v_F4_u_0_NegBig[3]={
   {-40, 0},
   {-40, 1},
   {-20, 0}};
NumTypeF4Point_t FC_v_F4_u_1_NegSmall[3]={
   {-40, 0},
   {-20, 1},
   {0, 0}};
NumTypeF4Point_t FC_v_F4_u_2_Zero[1]={
   {0, 1}};
NumTypeF4Point_t FC_v_F4_u_3_PosSmall[3]={
   {0, 0},
   {20, 1},
   {40, 0}};
NumTypeF4Point_t FC_v_F4_u_4_PosBig[3]={
   {20, 0},
   {40, 1},
   {40, 0}};


FuzzySetF4_t FC_v_F4_e_0[5]={
   {3, FC_v_F4_e_0_NegBig},
   {3, FC_v_F4_e_1_NegSmall},
   {3, FC_v_F4_e_2_Zero},
   {3, FC_v_F4_e_3_PosSmall},
   {3, FC_v_F4_e_4_PosBig}};

FuzzySetF4_t FC_v_F4_e_int_1[5]={
   {3, FC_v_F4_e_int_0_NegBig},
   {3, FC_v_F4_e_int_1_NegSmall},
   {1, FC_v_F4_e_int_2_Zero},
   {3, FC_v_F4_e_int_3_PosSmall},
   {3, FC_v_F4_e_int_4_PosBig}};
/*############################################################################*/
/*                              Input variables                               */
/*############################################################################*/

LinguisticInputVariableF4_t FC_v_F4_Input[2]={
   {5, FC_v_F4_e_0},
   {5, FC_v_F4_e_int_1}};


FuzzySetF4_t FC_v_F4_u_0[5]={
   {3, FC_v_F4_u_0_NegBig},
   {3, FC_v_F4_u_1_NegSmall},
   {1, FC_v_F4_u_2_Zero},
   {3, FC_v_F4_u_3_PosSmall},
   {3, FC_v_F4_u_4_PosBig}};
/*############################################################################*/
/*                              Output variables                              */
/*############################################################################*/

LinguisticOutputVariableF4_t FC_v_F4_Output[1]={
   {5, FC_v_F4_u_0, 0, 0}};
/*############################################################################*/
/*                         Premises of the rule base                          */
/*############################################################################*/

char FC_v_F4_RuleBase_pre[10*2]={
   1,0,
   2,0,
   4,0,
   5,0,
   3,0,
   3,3,
   0,2,
   0,1,
   0,4,
   0,5};

/*############################################################################*/
/*                        Conclusion of the rule base                         */
/*############################################################################*/

char FC_v_F4_RuleBase_con[10*1]={
   1,
   2,
   4,
   5,
   3,
   3,
   2,
   1,
   4,
   5};

/*############################################################################*/
/*                           Weighting of the rules                           */
/*############################################################################*/

NumTypeF4_t FC_v_F4_RuleBase_weight[10]={
   0.20000000298,
   0.20000000298,
   0.5,
   0.20000000298,
   0.5,
   0.600000023842,
   0.600000023842,
   0.600000023842,
   0.600000023842,
   0.600000023842};

/*############################################################################*/
/*                    All together in FuzzyControllerF4_t                     */
/*############################################################################*/
extern FuzzyControllerF4_t FC_v_F4_FC={
   2,
   1,
   10,
   FC_v_F4_Input,
   FC_v_F4_Output,
   FC_v_F4_RuleBase_pre,
   FC_v_F4_RuleBase_con,
   FC_v_F4_RuleBase_weight,
   MAX_MIN,
   DEFUZZY_COG,
   60,
   AND_MIN,
   OR_MAX};


/*############################################################################*/
/*                       Call this function to be sure                        */
/*                  to work with the correct number format.                   */
/*############################################################################*/


void FC_v_F4_SetNumType(void)
{
}


/*############################################################################*/
/*                           Structure of pointers                            */
/*           This structure is allocated in the xx_init() function            */
/*        and is needed for the calculation in the xx_calc() function.        */
/*############################################################################*/

FCMemF4_t FC_v_F4_FCMem;


/*############################################################################*/
/*                          Initializiation function                          */
/*                  Call this function before the others !!                   */
/*############################################################################*/


void FC_v_F4_init(void)
{
  FCF4_init(&FC_v_F4_FC, &FC_v_F4_FCMem);
}
/*############################################################################*/
/*                    Function representing the controller                    */
/*############################################################################*/


void FC_v_F4_calc(
       const NumTypeF4_t i0,
       const NumTypeF4_t i1,
       NumTypeF4_t *o0)
{
  NumTypeF4_t ai[2];
  NumTypeF4_t ao[1];
  ai[0]=i0;
  ai[1]=i1;
  FCF4_calc(&FC_v_F4_FC, &FC_v_F4_FCMem, ai, ao);
  *o0=ao[0];
}
/*############################################################################*/
/*                       Function to release the memory                       */
/*                     which was allocated by xx-init().                      */
/*############################################################################*/


void FC_v_F4_free(void)
{
  FCF4_free(&FC_v_F4_FC, &FC_v_F4_FCMem);
}
