/***************************************************************************
  This file was created by the program FALCO which is a module 
  of WinFACT (Windows Fuzzy And Control Tools).

  Instead of editing this file, modify FALCOs Source-File
  with FLOP and generate it once again.

  Generated by : Florian
            on : DESKTOP-N6QTDVR
  FALCO Version: 8.0.0.9
  Source-File  : C:\Users\Florian\Documents\SCHULE\Diplomarbeit\NeueCodeGenerierung\V3\FuzzyV3.fuz from:04.01.2020 12:44:50
  Timestamp    : 04.01.2020 12:46:13

  Description of the fuzzy controller implemented in this code:
  =============================================================

    Inputs: 1
     e_winkel

    Outputs: 1
     u_winkel

    Rules: 5

    Inferencemechanism: Max-Min
    Method of defuzzyfication: center of gravity (Intergration via 60 steps)
    Number format: 4 Byte IEEE float
***************************************************************************/

#include "FuzzyV3_F4.h"

/*############################################################################*/
/*                        Sets of all input variables                         */
/*############################################################################*/

NumTypeF4Point_t FuzzyV3_F4_e_winkel_0_NegBig[3]={
   {-30, 0},
   {-30, 1},
   {-15, 0}};
NumTypeF4Point_t FuzzyV3_F4_e_winkel_1_NegSmall[3]={
   {-30, 0},
   {-15, 1},
   {0, 0}};
NumTypeF4Point_t FuzzyV3_F4_e_winkel_2_Zero[3]={
   {-15, 0},
   {0, 1},
   {15, 0}};
NumTypeF4Point_t FuzzyV3_F4_e_winkel_3_PosSmall[3]={
   {0, 0},
   {15, 1},
   {30, 0}};
NumTypeF4Point_t FuzzyV3_F4_e_winkel_4_PosBig[3]={
   {15, 0},
   {30, 1},
   {30, 0}};

/*############################################################################*/
/*                        Sets of all output variables                        */
/*############################################################################*/

NumTypeF4Point_t FuzzyV3_F4_u_winkel_0_NegBig[3]={
   {-30, 0},
   {-30, 1},
   {-15, 0}};
NumTypeF4Point_t FuzzyV3_F4_u_winkel_1_NegSmall[3]={
   {-30, 0},
   {-15, 1},
   {0, 0}};
NumTypeF4Point_t FuzzyV3_F4_u_winkel_2_Zero[3]={
   {-15, 0},
   {0, 1},
   {15, 0}};
NumTypeF4Point_t FuzzyV3_F4_u_winkel_3_PosSmall[3]={
   {0, 0},
   {15, 1},
   {30, 0}};
NumTypeF4Point_t FuzzyV3_F4_u_winkel_4_PosBig[3]={
   {15, 0},
   {30, 1},
   {30, 0}};


FuzzySetF4_t FuzzyV3_F4_e_winkel_0[5]={
   {3, FuzzyV3_F4_e_winkel_0_NegBig},
   {3, FuzzyV3_F4_e_winkel_1_NegSmall},
   {3, FuzzyV3_F4_e_winkel_2_Zero},
   {3, FuzzyV3_F4_e_winkel_3_PosSmall},
   {3, FuzzyV3_F4_e_winkel_4_PosBig}};
/*############################################################################*/
/*                              Input variables                               */
/*############################################################################*/

LinguisticInputVariableF4_t FuzzyV3_F4_Input[1]={
   {5, FuzzyV3_F4_e_winkel_0}};


FuzzySetF4_t FuzzyV3_F4_u_winkel_0[5]={
   {3, FuzzyV3_F4_u_winkel_0_NegBig},
   {3, FuzzyV3_F4_u_winkel_1_NegSmall},
   {3, FuzzyV3_F4_u_winkel_2_Zero},
   {3, FuzzyV3_F4_u_winkel_3_PosSmall},
   {3, FuzzyV3_F4_u_winkel_4_PosBig}};
/*############################################################################*/
/*                              Output variables                              */
/*############################################################################*/

LinguisticOutputVariableF4_t FuzzyV3_F4_Output[1]={
   {5, FuzzyV3_F4_u_winkel_0, 0, 0}};
/*############################################################################*/
/*                         Premises of the rule base                          */
/*############################################################################*/

char FuzzyV3_F4_RuleBase_pre[5*1]={
   3,
   2,
   1,
   4,
   5};

/*############################################################################*/
/*                        Conclusion of the rule base                         */
/*############################################################################*/

char FuzzyV3_F4_RuleBase_con[5*1]={
   3,
   4,
   5,
   2,
   1};

/*############################################################################*/
/*                           Weighting of the rules                           */
/*############################################################################*/

NumTypeF4_t FuzzyV3_F4_RuleBase_weight[5]={
   1,
   1,
   1,
   1,
   1};

/*############################################################################*/
/*                    All together in FuzzyControllerF4_t                     */
/*############################################################################*/
extern FuzzyControllerF4_t FuzzyV3_F4_FC={
   1,
   1,
   5,
   FuzzyV3_F4_Input,
   FuzzyV3_F4_Output,
   FuzzyV3_F4_RuleBase_pre,
   FuzzyV3_F4_RuleBase_con,
   FuzzyV3_F4_RuleBase_weight,
   MAX_MIN,
   DEFUZZY_COG,
   60,
   AND_MIN,
   OR_MAX};


/*############################################################################*/
/*                       Call this function to be sure                        */
/*                  to work with the correct number format.                   */
/*############################################################################*/


void FuzzyV3_F4_SetNumType(void)
{
}


/*############################################################################*/
/*                           Structure of pointers                            */
/*           This structure is allocated in the xx_init() function            */
/*        and is needed for the calculation in the xx_calc() function.        */
/*############################################################################*/

FCMemF4_t FuzzyV3_F4_FCMem;


/*############################################################################*/
/*                          Initializiation function                          */
/*                  Call this function before the others !!                   */
/*############################################################################*/


void FuzzyV3_F4_init(void)
{
  FCF4_init(&FuzzyV3_F4_FC, &FuzzyV3_F4_FCMem);
}
/*############################################################################*/
/*                    Function representing the controller                    */
/*############################################################################*/


void FuzzyV3_F4_calc(
       const NumTypeF4_t i0,
       NumTypeF4_t *o0)
{
  NumTypeF4_t ai[1];
  NumTypeF4_t ao[1];
  ai[0]=i0;
  FCF4_calc(&FuzzyV3_F4_FC, &FuzzyV3_F4_FCMem, ai, ao);
  *o0=ao[0];
}
/*############################################################################*/
/*                       Function to release the memory                       */
/*                     which was allocated by xx-init().                      */
/*############################################################################*/


void FuzzyV3_F4_free(void)
{
  FCF4_free(&FuzzyV3_F4_FC, &FuzzyV3_F4_FCMem);
}
