/***************************************************************************
  This file was created by the program FALCO which is a module 
  of WinFACT (Windows Fuzzy And Control Tools).

  Instead of editing this file, modify FALCOs Source-File
  with FLOP and generate it once again.

  Generated by : Florian
            on : DESKTOP-N6QTDVR
  FALCO Version: 8.0.0.9
  Source-File  : C:\Users\Florian\Documents\SCHULE\Diplomarbeit\Fuzzy\FuzzyTry.fuz from:04.01.2020 19:04:16
  Timestamp    : 04.01.2020 20:04:49

  Description of the fuzzy controller implemented in this code:
  =============================================================

    Inputs: 2
     geschwindigkeit
     winkel

    Outputs: 2
     vOUT
     phiOUT

    Rules: 10

    Inferencemechanism: Max-Min
    Method of defuzzyfication: center of gravity (Intergration via 60 steps)
    Number format: 4 Byte IEEE float
***************************************************************************/

#include "FuzzyTry_F4.h"

/*############################################################################*/
/*                        Sets of all input variables                         */
/*############################################################################*/

NumTypeF4Point_t FuzzyTry_F4_geschwindigkeit_0_NegBig[3]={
   {-500, 0},
   {-500, 1},
   {-190, 0}};
NumTypeF4Point_t FuzzyTry_F4_geschwindigkeit_1_NegSmall[3]={
   {-500, 0},
   {-250, 1},
   {-100, 0}};
NumTypeF4Point_t FuzzyTry_F4_geschwindigkeit_2_Zero[3]={
   {-260, 0},
   {0, 1},
   {260, 0}};
NumTypeF4Point_t FuzzyTry_F4_geschwindigkeit_3_PosSmall[3]={
   {80, 0},
   {250, 1},
   {500, 0}};
NumTypeF4Point_t FuzzyTry_F4_geschwindigkeit_4_PosBig[3]={
   {190, 0},
   {500, 1},
   {500, 0}};

NumTypeF4Point_t FuzzyTry_F4_winkel_0_NegBig[3]={
   {-150, 0},
   {-150, 1},
   {-75, 0}};
NumTypeF4Point_t FuzzyTry_F4_winkel_1_NegSmall[3]={
   {-150, 0},
   {-75, 1},
   {0, 0}};
NumTypeF4Point_t FuzzyTry_F4_winkel_2_Zero[3]={
   {-75, 0},
   {0, 1},
   {75, 0}};
NumTypeF4Point_t FuzzyTry_F4_winkel_3_PosSmall[3]={
   {0, 0},
   {75, 1},
   {150, 0}};
NumTypeF4Point_t FuzzyTry_F4_winkel_4_PosBig[3]={
   {75, 0},
   {150, 1},
   {150, 0}};

/*############################################################################*/
/*                        Sets of all output variables                        */
/*############################################################################*/

NumTypeF4Point_t FuzzyTry_F4_vOUT_0_NegBig[3]={
   {-500, 0},
   {-500, 1},
   {-250, 0}};
NumTypeF4Point_t FuzzyTry_F4_vOUT_1_NegSmall[3]={
   {-500, 0},
   {-250, 1},
   {0, 0}};
NumTypeF4Point_t FuzzyTry_F4_vOUT_2_Zero[3]={
   {-250, 0},
   {0, 1},
   {250, 0}};
NumTypeF4Point_t FuzzyTry_F4_vOUT_3_PosSmall[3]={
   {0, 0},
   {250, 1},
   {500, 0}};
NumTypeF4Point_t FuzzyTry_F4_vOUT_4_PosBig[3]={
   {250, 0},
   {500, 1},
   {500, 0}};

NumTypeF4Point_t FuzzyTry_F4_phiOUT_0_NegBig[3]={
   {-150, 0},
   {-150, 1},
   {-75, 0}};
NumTypeF4Point_t FuzzyTry_F4_phiOUT_1_NegSmall[3]={
   {-150, 0},
   {-75, 1},
   {0, 0}};
NumTypeF4Point_t FuzzyTry_F4_phiOUT_2_Zero[3]={
   {-75, 0},
   {0, 1},
   {75, 0}};
NumTypeF4Point_t FuzzyTry_F4_phiOUT_3_PosSmall[3]={
   {0, 0},
   {75, 1},
   {150, 0}};
NumTypeF4Point_t FuzzyTry_F4_phiOUT_4_PosBig[3]={
   {75, 0},
   {150, 1},
   {150, 0}};


FuzzySetF4_t FuzzyTry_F4_geschwindigkeit_0[5]={
   {3, FuzzyTry_F4_geschwindigkeit_0_NegBig},
   {3, FuzzyTry_F4_geschwindigkeit_1_NegSmall},
   {3, FuzzyTry_F4_geschwindigkeit_2_Zero},
   {3, FuzzyTry_F4_geschwindigkeit_3_PosSmall},
   {3, FuzzyTry_F4_geschwindigkeit_4_PosBig}};

FuzzySetF4_t FuzzyTry_F4_winkel_1[5]={
   {3, FuzzyTry_F4_winkel_0_NegBig},
   {3, FuzzyTry_F4_winkel_1_NegSmall},
   {3, FuzzyTry_F4_winkel_2_Zero},
   {3, FuzzyTry_F4_winkel_3_PosSmall},
   {3, FuzzyTry_F4_winkel_4_PosBig}};
/*############################################################################*/
/*                              Input variables                               */
/*############################################################################*/

LinguisticInputVariableF4_t FuzzyTry_F4_Input[2]={
   {5, FuzzyTry_F4_geschwindigkeit_0},
   {5, FuzzyTry_F4_winkel_1}};


FuzzySetF4_t FuzzyTry_F4_vOUT_0[5]={
   {3, FuzzyTry_F4_vOUT_0_NegBig},
   {3, FuzzyTry_F4_vOUT_1_NegSmall},
   {3, FuzzyTry_F4_vOUT_2_Zero},
   {3, FuzzyTry_F4_vOUT_3_PosSmall},
   {3, FuzzyTry_F4_vOUT_4_PosBig}};

FuzzySetF4_t FuzzyTry_F4_phiOUT_1[5]={
   {3, FuzzyTry_F4_phiOUT_0_NegBig},
   {3, FuzzyTry_F4_phiOUT_1_NegSmall},
   {3, FuzzyTry_F4_phiOUT_2_Zero},
   {3, FuzzyTry_F4_phiOUT_3_PosSmall},
   {3, FuzzyTry_F4_phiOUT_4_PosBig}};
/*############################################################################*/
/*                              Output variables                              */
/*############################################################################*/

LinguisticOutputVariableF4_t FuzzyTry_F4_Output[2]={
   {5, FuzzyTry_F4_vOUT_0, 0, 0},
   {5, FuzzyTry_F4_phiOUT_1, 0, 0}};
/*############################################################################*/
/*                         Premises of the rule base                          */
/*############################################################################*/

char FuzzyTry_F4_RuleBase_pre[10*2]={
   3,0,
   4,0,
   5,0,
   2,0,
   1,0,
   0,1,
   0,2,
   0,3,
   0,5,
   0,4};

/*############################################################################*/
/*                        Conclusion of the rule base                         */
/*############################################################################*/

char FuzzyTry_F4_RuleBase_con[10*2]={
   3,0,
   4,0,
   5,0,
   2,0,
   1,0,
   0,1,
   0,2,
   0,3,
   0,5,
   0,4};

/*############################################################################*/
/*                           Weighting of the rules                           */
/*############################################################################*/

NumTypeF4_t FuzzyTry_F4_RuleBase_weight[10]={
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1};

/*############################################################################*/
/*                    All together in FuzzyControllerF4_t                     */
/*############################################################################*/
extern FuzzyControllerF4_t FuzzyTry_F4_FC={
   2,
   2,
   10,
   FuzzyTry_F4_Input,
   FuzzyTry_F4_Output,
   FuzzyTry_F4_RuleBase_pre,
   FuzzyTry_F4_RuleBase_con,
   FuzzyTry_F4_RuleBase_weight,
   MAX_MIN,
   DEFUZZY_COG,
   60,
   AND_MIN,
   OR_MAX};


/*############################################################################*/
/*                       Call this function to be sure                        */
/*                  to work with the correct number format.                   */
/*############################################################################*/


void FuzzyTry_F4_SetNumType(void)
{
}


/*############################################################################*/
/*                           Structure of pointers                            */
/*           This structure is allocated in the xx_init() function            */
/*        and is needed for the calculation in the xx_calc() function.        */
/*############################################################################*/

FCMemF4_t FuzzyTry_F4_FCMem;


/*############################################################################*/
/*                          Initializiation function                          */
/*                  Call this function before the others !!                   */
/*############################################################################*/


void FuzzyTry_F4_init(void)
{
  FCF4_init(&FuzzyTry_F4_FC, &FuzzyTry_F4_FCMem);
}
/*############################################################################*/
/*                    Function representing the controller                    */
/*############################################################################*/


void FuzzyTry_F4_calc(
       const NumTypeF4_t i0,
       const NumTypeF4_t i1,
       NumTypeF4_t *o0,
       NumTypeF4_t *o1)
{
  NumTypeF4_t ai[2];
  NumTypeF4_t ao[2];
  ai[0]=i0;
  ai[1]=i1;
  FCF4_calc(&FuzzyTry_F4_FC, &FuzzyTry_F4_FCMem, ai, ao);
  *o0=ao[0];
  *o1=ao[1];
}
/*############################################################################*/
/*                       Function to release the memory                       */
/*                     which was allocated by xx-init().                      */
/*############################################################################*/


void FuzzyTry_F4_free(void)
{
  FCF4_free(&FuzzyTry_F4_FC, &FuzzyTry_F4_FCMem);
}
