/***************************************************************************
  This file was created by the program FALCO which is a module 
  of WinFACT (Windows Fuzzy And Control Tools).

  Instead of editing this file, modify FALCOs Source-File
  with FLOP and generate it once again.

  Generated by : Florian
            on : DESKTOP-N6QTDVR
  FALCO Version: 8.0.0.9
  Source-File  : C:\Users\Florian\Documents\SCHULE\5AHET\Diplomarbeit\WinFact\LKWRangierenFuzzy\rangierFuzzy.fuz from:03.11.2019 20:06:00
  Timestamp    : 17.11.2019 08:15:29

  Description of the fuzzy controller implemented in this code:
  =============================================================

    Inputs: 2
     e1
     e2

    Outputs: 2
     a1
     a2

    Rules: 9

    Inferencemechanism: Max-Min
    Method of defuzzyfication: center of gravity (Intergration via 60 steps)
    Number format: 4 Byte IEEE float
***************************************************************************/

#include "rangierFuzzy_F4.h"

/*############################################################################*/
/*                        Sets of all input variables                         */
/*############################################################################*/

static const NumTypeF4Point_t rangierFuzzy_F4_e1_0_NegBig[3]={
   {-100, 0},
   {-100, 1},
   {-50, 0}};
static const NumTypeF4Point_t rangierFuzzy_F4_e1_1_NegSmall[3]={
   {-100, 0},
   {-50, 1},
   {0, 0}};
static const NumTypeF4Point_t rangierFuzzy_F4_e1_2_Zero[3]={
   {-40, 0},
   {0, 1},
   {42, 0}};
static const NumTypeF4Point_t rangierFuzzy_F4_e1_3_PosSmall[3]={
   {0, 0},
   {50, 1},
   {100, 0}};
static const NumTypeF4Point_t rangierFuzzy_F4_e1_4_PosBig[3]={
   {50, 0},
   {100, 1},
   {100, 0}};

static const NumTypeF4Point_t rangierFuzzy_F4_e2_0_NegBig[3]={
   {-100, 0},
   {-100, 1},
   {-50, 0}};
static const NumTypeF4Point_t rangierFuzzy_F4_e2_1_NegSmall[3]={
   {-100, 0},
   {-50, 1},
   {0, 0}};
static const NumTypeF4Point_t rangierFuzzy_F4_e2_2_Zero[3]={
   {-50, 0},
   {0, 1},
   {50, 0}};
static const NumTypeF4Point_t rangierFuzzy_F4_e2_3_PosSmall[3]={
   {0, 0},
   {50, 1},
   {100, 0}};
static const NumTypeF4Point_t rangierFuzzy_F4_e2_4_PosBig[3]={
   {50, 0},
   {100, 1},
   {100, 0}};

/*############################################################################*/
/*                        Sets of all output variables                        */
/*############################################################################*/

static const NumTypeF4Point_t rangierFuzzy_F4_a1_0_NegBig[3]={
   {-100, 0},
   {-100, 1},
   {-50, 0}};
static const NumTypeF4Point_t rangierFuzzy_F4_a1_1_NegSmall[3]={
   {-100, 0},
   {-50, 1},
   {0, 0}};
static const NumTypeF4Point_t rangierFuzzy_F4_a1_2_Zero[3]={
   {-50, 0},
   {0, 1},
   {50, 0}};
static const NumTypeF4Point_t rangierFuzzy_F4_a1_3_PosSmall[3]={
   {0, 0},
   {50, 1},
   {100, 0}};
static const NumTypeF4Point_t rangierFuzzy_F4_a1_4_PosBig[3]={
   {50, 0},
   {100, 1},
   {100, 0}};

static const NumTypeF4Point_t rangierFuzzy_F4_a2_0_NegBig[3]={
   {-100, 0},
   {-100, 1},
   {-50, 0}};
static const NumTypeF4Point_t rangierFuzzy_F4_a2_1_NegSmall[3]={
   {-100, 0},
   {-50, 1},
   {0, 0}};
static const NumTypeF4Point_t rangierFuzzy_F4_a2_2_Zero[3]={
   {-50, 0},
   {0, 1},
   {50, 0}};
static const NumTypeF4Point_t rangierFuzzy_F4_a2_3_PosSmall[3]={
   {0, 0},
   {50, 1},
   {100, 0}};
static const NumTypeF4Point_t rangierFuzzy_F4_a2_4_PosBig[3]={
   {50, 0},
   {100, 1},
   {100, 0}};


static const FuzzySetF4_t rangierFuzzy_F4_e1_0[5]={
   {3, rangierFuzzy_F4_e1_0_NegBig},
   {3, rangierFuzzy_F4_e1_1_NegSmall},
   {3, rangierFuzzy_F4_e1_2_Zero},
   {3, rangierFuzzy_F4_e1_3_PosSmall},
   {3, rangierFuzzy_F4_e1_4_PosBig}};

static const FuzzySetF4_t rangierFuzzy_F4_e2_1[5]={
   {3, rangierFuzzy_F4_e2_0_NegBig},
   {3, rangierFuzzy_F4_e2_1_NegSmall},
   {3, rangierFuzzy_F4_e2_2_Zero},
   {3, rangierFuzzy_F4_e2_3_PosSmall},
   {3, rangierFuzzy_F4_e2_4_PosBig}};
/*############################################################################*/
/*                              Input variables                               */
/*############################################################################*/

static const LinguisticInputVariableF4_t rangierFuzzy_F4_Input[2]={
   {5, rangierFuzzy_F4_e1_0},
   {5, rangierFuzzy_F4_e2_1}};


static const FuzzySetF4_t rangierFuzzy_F4_a1_0[5]={
   {3, rangierFuzzy_F4_a1_0_NegBig},
   {3, rangierFuzzy_F4_a1_1_NegSmall},
   {3, rangierFuzzy_F4_a1_2_Zero},
   {3, rangierFuzzy_F4_a1_3_PosSmall},
   {3, rangierFuzzy_F4_a1_4_PosBig}};

static const FuzzySetF4_t rangierFuzzy_F4_a2_1[5]={
   {3, rangierFuzzy_F4_a2_0_NegBig},
   {3, rangierFuzzy_F4_a2_1_NegSmall},
   {3, rangierFuzzy_F4_a2_2_Zero},
   {3, rangierFuzzy_F4_a2_3_PosSmall},
   {3, rangierFuzzy_F4_a2_4_PosBig}};
/*############################################################################*/
/*                              Output variables                              */
/*############################################################################*/

static const LinguisticOutputVariableF4_t rangierFuzzy_F4_Output[2]={
   {5, rangierFuzzy_F4_a1_0, 0, 0},
   {5, rangierFuzzy_F4_a2_1, 0, 0}};
/*############################################################################*/
/*                         Premises of the rule base                          */
/*############################################################################*/

static const char rangierFuzzy_F4_RuleBase_pre[9*2]={
   3,3,
   4,0,
   5,0,
   2,0,
   1,0,
   0,4,
   0,5,
   0,1,
   0,2};

/*############################################################################*/
/*                        Conclusion of the rule base                         */
/*############################################################################*/

static const char rangierFuzzy_F4_RuleBase_con[9*2]={
   3,3,
   4,0,
   5,0,
   2,0,
   1,0,
   0,4,
   0,5,
   0,1,
   0,2};

/*############################################################################*/
/*                           Weighting of the rules                           */
/*############################################################################*/

static const NumTypeF4_t rangierFuzzy_F4_RuleBase_weight[9]={
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1,
   1};

/*############################################################################*/
/*                    All together in FuzzyControllerF4_t                     */
/*############################################################################*/
static const FuzzyControllerF4_t rangierFuzzy_F4_FC={
   2,
   2,
   9,
   rangierFuzzy_F4_Input,
   rangierFuzzy_F4_Output,
   rangierFuzzy_F4_RuleBase_pre,
   rangierFuzzy_F4_RuleBase_con,
   rangierFuzzy_F4_RuleBase_weight,
   MAX_MIN,
   DEFUZZY_COG,
   60,
   AND_MIN,
   OR_MAX};


/*############################################################################*/
/*                       Call this function to be sure                        */
/*                  to work with the correct number format.                   */
/*############################################################################*/


void rangierFuzzy_F4_SetNumType(void)
{
}


/*############################################################################*/
/*                           Structure of pointers                            */
/*           This structure is allocated in the xx_init() function            */
/*        and is needed for the calculation in the xx_calc() function.        */
/*############################################################################*/

static FCMemF4_t rangierFuzzy_F4_FCMem;


/*############################################################################*/
/*                          Initializiation function                          */
/*                  Call this function before the others !!                   */
/*############################################################################*/


void rangierFuzzy_F4_init(void)
{
  FCF4_init(&rangierFuzzy_F4_FC, &rangierFuzzy_F4_FCMem);
}
/*############################################################################*/
/*                    Function representing the controller                    */
/*############################################################################*/


void rangierFuzzy_F4_calc(
       const NumTypeF4_t i0,
       const NumTypeF4_t i1,
       NumTypeF4_t *o0,
       NumTypeF4_t *o1)
{
  NumTypeF4_t ai[2];
  NumTypeF4_t ao[2];
  ai[0]=i0;
  ai[1]=i1;
  FCF4_calc(&rangierFuzzy_F4_FC, &rangierFuzzy_F4_FCMem, ai, ao);
  *o0=ao[0];
  *o1=ao[1];
}
/*############################################################################*/
/*                       Function to release the memory                       */
/*                     which was allocated by xx-init().                      */
/*############################################################################*/


void rangierFuzzy_F4_free(void)
{
  FCF4_free(&rangierFuzzy_F4_FC, &rangierFuzzy_F4_FCMem);
}
