/***************************************************************************
  This file was created by the program FALCO which is a module 
  of WinFACT (Windows Fuzzy And Control Tools).

  Instead of editing this file, modify FALCOs Source-File
  with FLOP and generate it once again.

  Generated by : Florian
            on : DESKTOP-N6QTDVR
  FALCO Version: 8.0.0.9
  Source-File  : C:\Users\Florian\Documents\SCHULE\Diplomarbeit\Fuzzy\Winfact\testdiplom.fuz from:22.10.2019 16:52:52
  Timestamp    : 22.10.2019 17:01:42

  Description of the fuzzy controller implemented in this code:
  =============================================================

    Inputs: 1
     e

    Outputs: 1
     u

    Rules: 3

    Inferencemechanism: Max-Min
    Method of defuzzyfication: center of gravity (Intergration via 60 steps)
    Number format: 4 Byte IEEE float
***************************************************************************/

#include "testdiplom_F4.h"

/*############################################################################*/
/*                        Sets of all input variables                         */
/*############################################################################*/

static const NumTypeF4Point_t testdiplom_F4_e_0_NegBig[3]={
   {-1, 0},
   {-1, 1},
   {-0.5, 0}};
static const NumTypeF4Point_t testdiplom_F4_e_1_NegSmall[3]={
   {-1, 0},
   {-0.5, 1},
   {0, 0}};
static const NumTypeF4Point_t testdiplom_F4_e_2_Zero[3]={
   {-0.5, 0},
   {0, 1},
   {0.5, 0}};
static const NumTypeF4Point_t testdiplom_F4_e_3_PosSmall[3]={
   {0, 0},
   {0.5, 1},
   {1, 0}};
static const NumTypeF4Point_t testdiplom_F4_e_4_PosBig[3]={
   {0.5, 0},
   {1, 1},
   {1, 0}};

/*############################################################################*/
/*                        Sets of all output variables                        */
/*############################################################################*/

static const NumTypeF4Point_t testdiplom_F4_u_0_NegBig[3]={
   {-1, 0},
   {-1, 1},
   {-0.5, 0}};
static const NumTypeF4Point_t testdiplom_F4_u_1_NegSmall[3]={
   {-1, 0},
   {-0.5, 1},
   {0, 0}};
static const NumTypeF4Point_t testdiplom_F4_u_2_Zero[3]={
   {-0.5, 0},
   {0, 1},
   {0.5, 0}};
static const NumTypeF4Point_t testdiplom_F4_u_3_PosSmall[3]={
   {0, 0},
   {0.5, 1},
   {1, 0}};
static const NumTypeF4Point_t testdiplom_F4_u_4_PosBig[3]={
   {0.5, 0},
   {1, 1},
   {1, 0}};


static const FuzzySetF4_t testdiplom_F4_e_0[5]={
   {3, testdiplom_F4_e_0_NegBig},
   {3, testdiplom_F4_e_1_NegSmall},
   {3, testdiplom_F4_e_2_Zero},
   {3, testdiplom_F4_e_3_PosSmall},
   {3, testdiplom_F4_e_4_PosBig}};
/*############################################################################*/
/*                              Input variables                               */
/*############################################################################*/

static const LinguisticInputVariableF4_t testdiplom_F4_Input[1]={
   {5, testdiplom_F4_e_0}};


static const FuzzySetF4_t testdiplom_F4_u_0[5]={
   {3, testdiplom_F4_u_0_NegBig},
   {3, testdiplom_F4_u_1_NegSmall},
   {3, testdiplom_F4_u_2_Zero},
   {3, testdiplom_F4_u_3_PosSmall},
   {3, testdiplom_F4_u_4_PosBig}};
/*############################################################################*/
/*                              Output variables                              */
/*############################################################################*/

static const LinguisticOutputVariableF4_t testdiplom_F4_Output[1]={
   {5, testdiplom_F4_u_0, 0, 0}};
/*############################################################################*/
/*                         Premises of the rule base                          */
/*############################################################################*/

static const char testdiplom_F4_RuleBase_pre[3*1]={
   2,
   3,
   4};

/*############################################################################*/
/*                        Conclusion of the rule base                         */
/*############################################################################*/

static const char testdiplom_F4_RuleBase_con[3*1]={
   2,
   3,
   4};

/*############################################################################*/
/*                           Weighting of the rules                           */
/*############################################################################*/

static const NumTypeF4_t testdiplom_F4_RuleBase_weight[3]={
   1,
   1,
   1};

/*############################################################################*/
/*                    All together in FuzzyControllerF4_t                     */
/*############################################################################*/
static const FuzzyControllerF4_t testdiplom_F4_FC={
   1,
   1,
   3,
   testdiplom_F4_Input,
   testdiplom_F4_Output,
   testdiplom_F4_RuleBase_pre,
   testdiplom_F4_RuleBase_con,
   testdiplom_F4_RuleBase_weight,
   MAX_MIN,
   DEFUZZY_COG,
   60,
   AND_MIN,
   OR_MAX};


/*############################################################################*/
/*                       Call this function to be sure                        */
/*                  to work with the correct number format.                   */
/*############################################################################*/


void testdiplom_F4_SetNumType(void)
{
}


/*############################################################################*/
/*                           Structure of pointers                            */
/*           This structure is allocated in the xx_init() function            */
/*        and is needed for the calculation in the xx_calc() function.        */
/*############################################################################*/

static FCMemF4_t testdiplom_F4_FCMem;


/*############################################################################*/
/*                          Initializiation function                          */
/*                  Call this function before the others !!                   */
/*############################################################################*/


void testdiplom_F4_init(void)
{
  FCF4_init(&testdiplom_F4_FC, &testdiplom_F4_FCMem);
}
/*############################################################################*/
/*                    Function representing the controller                    */
/*############################################################################*/


void testdiplom_F4_calc(
       const NumTypeF4_t i0,
       NumTypeF4_t *o0)
{
  NumTypeF4_t ai[1];
  NumTypeF4_t ao[1];
  ai[0]=i0;
  FCF4_calc(&testdiplom_F4_FC, &testdiplom_F4_FCMem, ai, ao);
  *o0=ao[0];
}
/*############################################################################*/
/*                       Function to release the memory                       */
/*                     which was allocated by xx-init().                      */
/*############################################################################*/


void testdiplom_F4_free(void)
{
  FCF4_free(&testdiplom_F4_FC, &testdiplom_F4_FCMem);
}
